server:
  port: 11010

spring:
  application:
    name: social-eureka-server

security:
  basic:
    enabled: true # 启用身份认证
  user:
    name: jbzm # 定义用户名
    password: jbzm521 # 定义密码

logging:
  level: debug

